### ISSUE TITLE
💚 Implement Crate Publication in CI Upon Release

### ISSUE THREAD

**Issue by ccamel** [axone-protocol/contracts#527]
## Issue

As of now, crates are not published to [crates.io](https://crates.io/) or any registry, making it difficult for users and developers to access the technical information of the latest versions of our smart contracts (and libraries).

## Todo

Implementation the automated crate publication as part of our CI process upon release.

**Comment by ErikssonJoakim** [comment]
Linked PR: 
- https://github.com/axone-protocol/contracts/pull/569
