### ISSUE TITLE
🛡️ Arithmetic Overflow in CosmWasm-Std Affects OKP4 Contracts

### ISSUE THREAD

**Issue by ccamel** [axone-protocol/contracts#553]
> [!NOTE]
> **Severity**: Medium
> **target**: [v5.0.0 - Commit: cde785fbd2dad71608d53f8524e0ef8c8f8178af](https://github.com/axone-protocol/contracts/releases/tag/v5.0.0)
> **Ref**: OKP4 CosmWasm Audit Report v1.0 - 02-05-2024 - [BlockApex](https://www.blockapex.io/)

## Description

The OKP4 ecosystem is currently using version 1.5.3 of the cosmwasm-std library, which has been found to contain arithmetic overflow issues as detailed in advisory [CWA-2024-002](https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2024-002.md). This vulnerability affects all contracts that perform arithmetic operations, including Objectarium, Cognitarium, Dataverse, and Law Stone. Arithmetic overflows can alter the expected behavior of smart contracts by causing computations to wrap incorrectly.

## Impact

This overflow can lead to incorrect data processing, resulting in potential state corruption or mismanagement of contract logic. It directly threatens the reliability and effectiveness of the contract's intended functionalities.

## Recommendation

Upgrade the cosmwasm-std library to the latest patched version as recommended in the [advisory](https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2024-002.md).

**Comment by bdeneux** [comment]
Fixed by @dependabot PR : https://github.com/axone-protocol/contracts/pull/533

**Comment by amimart** [comment]
> Fixed by @dependabot PR : #533

Yep closing it :)
