### ISSUE TITLE
🛡️ Inadequate Input Validation in Objectarium Contract Instantiation

### ISSUE THREAD

**Issue by ccamel** [axone-protocol/contracts#560]
> [!NOTE]
> **Severity**: Low
> **target**: [v5.0.0 - Commit: cde785fbd2dad71608d53f8524e0ef8c8f8178af](https://github.com/axone-protocol/contracts/releases/tag/v5.0.0)
> **Ref**: OKP4 CosmWasm Audit Report v1.0 - 02-05-2024 - [BlockApex](https://www.blockapex.io/)

## Description

The instantiation process in the Objectarium contract lacks comprehensive input validation, specifically for the parameters associated with bucket configuration and limits. This deficiency may lead to configurations that render the contract functionally ineffective or vulnerable to misuse. The `try_new` method in the Bucket class currently only checks for an empty bucket name, overlooking critical validations on the numerical limits set for the bucket.

## Recommendation

Enhance the validation logic within the `Bucket::try_new` method to include checks on all parameters.

**Comment by bdeneux** [comment]
> > For the `BucketLimit` object, I don't see any additional checks that could be added, since setting a 0 value is considered as no limit (default value).
> 
> @bdeneux Are you sure about the 0 considered as no limit?

@amimart Sorry, you're right, according to the documentation it's not the zero value that indicate no limit but omitted value. 

https://github.com/axone-protocol/contracts/blob/9d0958df573c13b59ca70319e7cc137cf470c57c/contracts/axone-objectarium/src/msg.rs#L300

### `PaginationConfig` 

✅ Ok with your propositions

### `BucketConfig`

We need to check the behavior but according to the documentation, setting empty array is the same as omit this setting parameter (It's mean that all compressions algorithms are allowed) so is not necessary to check this configuration, except if we want to change the behavior and says that setting empty `accepted_compression_algorithm` is an incorrect configuration.

https://github.com/axone-protocol/contracts/blob/9d0958df573c13b59ca70319e7cc137cf470c57c/contracts/axone-objectarium/src/msg.rs#L268-L280

### `BucketLimits`

✅ Ok for those configurations checks. For the `max_objects_pins`, there is no interest being set to 0 but it's possible, I don't know too what is the best option 🤷.
