### ISSUE TITLE
🛡️ Insufficient Error Handling in Object Access Within Objectarium

### ISSUE THREAD

**Issue by ccamel** [axone-protocol/contracts#561]
> [!NOTE]
> **Severity**: Info
> **target**: [v5.0.0 - Commit: cde785fbd2dad71608d53f8524e0ef8c8f8178af](https://github.com/axone-protocol/contracts/releases/tag/v5.0.0)
> **Ref**: OKP4 CosmWasm Audit Report v1.0 - 02-05-2024 - [BlockApex](https://www.blockapex.io/)

## Description

The `pin_object` function in the Objectarium contract lacks preemptive checks to confirm the existence of an object before attempting operations on it. This oversight leads to attempts to manipulate non-existent objects, resulting in generic errors which are not descriptive of the actual issue. This issue is also evident in similar operations, such as `forget_object`, where object existence is assumed rather than verified before proceeding with further logic.

## Recommendation

Implement and enforce existence checks before performing any operations on objects within the contract.

**Comment by bdeneux** [comment]
## 🔎 Analysis 

### 📌 `pin_object`

The current implementation of the `pin_object` message already includes implicit error handling for non-existing or invalid `object_id`. This is managed through storage querying, and the unit tests already verify this behavior. When an error occurs, it returns a `StdError::not_found` error through `ContractError::Std`.

https://github.com/axone-protocol/contracts/blob/2ed6cdc3165898cd09a511af16d96cbf1dc80dd5/contracts/axone-objectarium/src/contract.rs#L173

https://github.com/axone-protocol/contracts/blob/2ed6cdc3165898cd09a511af16d96cbf1dc80dd5/contracts/axone-objectarium/src/contract.rs#L1508-L1526

### 📌 `unpin_object`

The `unpin_object` message follows a similar pattern, with error handling for non-existing or invalid `object_id`.

https://github.com/axone-protocol/contracts/blob/2ed6cdc3165898cd09a511af16d96cbf1dc80dd5/contracts/axone-objectarium/src/contract.rs#L1773-L1795

### 🗑 `forget_object` 

The `forget_object` message also includes error handling for non-existing or invalid `object_id`.

https://github.com/axone-protocol/contracts/blob/2ed6cdc3165898cd09a511af16d96cbf1dc80dd5/contracts/axone-objectarium/src/contract.rs#L2278-L2299


## 📈 Suggested Improvement

To enhance the clarity of error messages, we could consider replacing the generic `Std` error with a custom contract error, similar to [`ContractError::ObjectPinned`](https://github.com/axone-protocol/contracts/blob/main/contracts/axone-objectarium/src/error.rs#L15). For instance, we could introduce `ContractError::ObjectNotFound` to handle cases where the `object_id` does not exist.

@ccamel, @amimart

**Comment by amimart** [comment]
> To enhance the clarity of error messages, we could consider replacing the generic `Std` error with a custom contract error, similar to [`ContractError::ObjectPinned`](https://github.com/axone-protocol/contracts/blob/main/contracts/axone-objectarium/src/error.rs#L15). For instance, we could introduce `ContractError::ObjectNotFound` to handle cases where the `object_id` does not exist.

In my sense I'd rather use existing well known types if they suit, and the `StdError::NotFound` carry the targeted type so providing a specific `ContractError::ObjectNotFound` doesn't bring more value I think.

Actually I don't see this issue relevant because the checks and the errors are already here and pretty expressive, I don't see how we can do better.. What do you think? I'd be in favour to close this one

**Comment by ccamel** [comment]
@amimart I share your point of view. The standard `StdError::NotFound` exception conveys a sufficient level of information given the context in which it is used. I'd also be in favour of closing the ticket.

**Comment by amimart** [comment]
Ok let's closing it :)
