### ISSUE TITLE
♻️ Rename "metadata" field in SubmitClaims struct to "claims"

### ISSUE THREAD

**Issue by ccamel** [axone-protocol/contracts#580]
## Proposal

The `SubmitClaims` struct currently has a field named `metadata`. This name might be misleading as it conveys the idea of a data about data, which is not the quite the case for this action.

```rust
    SubmitClaims {
        /// The serialized metadata intended for attachment.
        /// This metadata should adhere to the format specified in the `format` field.
        metadata: Binary,
        /// RDF dataset serialization format for the metadata.
        /// If not provided, the default format is [N-Quads](https://www.w3.org/TR/n-quads/) format.
        format: Option<RdfDatasetFormat>,
    },
```

## Proposal

For clarity and precision, I propose to rename the `metadata` field to `claims` as  a _claim_ refers to a piece of information about an entity (such as a user, a service) that can be provided by one party and is potentially verifiable.

## Impact

- *positive*: this change will make the code more readable and self-explanatory
- *negative*: this change introduces a breaking-change in the contract
- *neutral*: none

**Comment by amimart** [comment]
Good catch, I'm 100% ok with that!
